-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1:3306
-- Üretim Zamanı: 15 Ağu 2021, 19:37:42
-- Sunucu sürümü: 5.7.31
-- PHP Sürümü: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `offers`
--
CREATE DATABASE IF NOT EXISTS `offers` DEFAULT CHARACTER SET utf8 COLLATE utf8_turkish_ci;
USE `offers`;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `ayar`
--

CREATE TABLE IF NOT EXISTS `ayar` (
  `ayar_id` int(11) NOT NULL AUTO_INCREMENT,
  `ayar_baslik` varchar(100) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_description` varchar(255) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_keywords` varchar(255) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_facebook` varchar(150) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_instagram` varchar(150) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_twitter` varchar(150) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_youtube` varchar(150) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_msunucu` varchar(100) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_mport` varchar(4) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_mkadi` varchar(100) COLLATE utf8_turkish_ci NOT NULL,
  `ayar_msifre` varchar(20) COLLATE utf8_turkish_ci NOT NULL,
  PRIMARY KEY (`ayar_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `ayar`
--

INSERT INTO `ayar` (`ayar_id`, `ayar_baslik`, `ayar_description`, `ayar_keywords`, `ayar_facebook`, `ayar_instagram`, `ayar_twitter`, `ayar_youtube`, `ayar_msunucu`, `ayar_mport`, `ayar_mkadi`, `ayar_msifre`) VALUES
(1, 'E-Ticaret Sitesi Çalışması', 'E-Ticaret Site çalışması üstüne kodlanmış sayfadır.', 'PHP,MYSQL,HTML,E-TİCARET', 'https://facebook.com', 'bedran.ozcan', '', '', 'smtp.gmail.com', '123', 'deneme@abc.com', '1234');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kullanici`
--

CREATE TABLE IF NOT EXISTS `kullanici` (
  `kullanici_id` int(11) NOT NULL AUTO_INCREMENT,
  `kullanici_mail` varchar(150) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_sifre` varchar(20) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_sifreunuttum` varchar(20) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_adsoyad` varchar(100) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_tc` varchar(11) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_adres` text COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_telefon` varchar(15) COLLATE utf8_turkish_ci NOT NULL,
  `kullanici_yetki` int(1) NOT NULL,
  `kullanici_kayit` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `kullanici_songiris` timestamp NOT NULL,
  PRIMARY KEY (`kullanici_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `kullanici`
--

INSERT INTO `kullanici` (`kullanici_id`, `kullanici_mail`, `kullanici_sifre`, `kullanici_sifreunuttum`, `kullanici_adsoyad`, `kullanici_tc`, `kullanici_adres`, `kullanici_telefon`, `kullanici_yetki`, `kullanici_kayit`, `kullanici_songiris`) VALUES
(1, 'admin@abc.com', 'qwe', '', 'Bedran Özcan', '11111111111', 'asdasdasdasdasd', '123456789', 1, '2021-08-14 17:36:39', '2021-08-15 19:28:37');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `offers`
--

CREATE TABLE IF NOT EXISTS `offers` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Teklif Id si',
  `productId` int(11) DEFAULT NULL COMMENT 'Ürün Id si',
  `offerHead` varchar(255) COLLATE utf8_turkish_ci DEFAULT NULL COMMENT 'Teklif açıklaması',
  `offerValue` varchar(255) COLLATE utf8_turkish_ci DEFAULT NULL COMMENT 'Teklif para değeri',
  `offerCreateTime` datetime DEFAULT NULL COMMENT 'Teklif Oluşturulma Tarihi',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `productId` (`productId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci ROW_FORMAT=DYNAMIC;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `productcategories`
--

CREATE TABLE IF NOT EXISTS `productcategories` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Ürün Kategori Id si',
  `category` varchar(255) COLLATE utf8_turkish_ci DEFAULT NULL COMMENT 'Ürün Kategori Değeri',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci ROW_FORMAT=DYNAMIC;

--
-- Tablo döküm verisi `productcategories`
--

INSERT INTO `productcategories` (`id`, `category`) VALUES
(1, 'DEMİR ÇELİK'),
(2, 'ELEKTRONİK MALZEMELERİ'),
(3, 'ELEKTRİK MOTORLARI'),
(4, 'REDÜKTÖR'),
(5, 'RULMAN, KEÇE VE KAYIŞ'),
(6, 'HIRDAVAT'),
(7, 'LAZER KESİM VE PLAZMA ÜRÜNLERİ'),
(8, 'SANAYİ MAKİNALARI'),
(9, 'KALIP SANAYİ'),
(10, 'DİŞLİ SANAYİ'),
(11, 'ALÜMİNYUM');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Ürün Id si',
  `categoryId` int(11) DEFAULT NULL COMMENT 'Ürünün bağlı olduğu kategori id si',
  `productName` varchar(255) COLLATE utf8_turkish_ci DEFAULT NULL COMMENT 'Ürün adı',
  `productsPrice` float DEFAULT NULL,
  `productsTop` tinyint(20) DEFAULT NULL,
  `offerCreateTime` datetime DEFAULT NULL COMMENT 'Ürün Teklif Oluşturabilme Tarihi',
  `offerFinishedTime` datetime DEFAULT NULL COMMENT 'Ürün teklif süre sonu tarihi',
  `productImage` varchar(255) COLLATE utf8_turkish_ci DEFAULT NULL COMMENT 'Ürün resim alanı',
  `productDescription` text COLLATE utf8_turkish_ci COMMENT 'Ürün açıklaması',
  `productSubDescription` text COLLATE utf8_turkish_ci COMMENT 'Ürün alt açıklaması',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `categoryId` (`categoryId`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci ROW_FORMAT=DYNAMIC;

--
-- Tablo döküm verisi `products`
--

INSERT INTO `products` (`id`, `categoryId`, `productName`, `productsPrice`, `productsTop`, `offerCreateTime`, `offerFinishedTime`, `productImage`, `productDescription`, `productSubDescription`) VALUES
(1, 1, 'Lorem ipsum dolor sit amet', NULL, NULL, '2020-05-02 21:48:54', '2020-05-08 21:48:59', 'http://alimsatimcim.com/mobil/874223191.jpeg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.'),
(2, 1, 'Lorem ipsum dolor sit amet', NULL, NULL, '2020-05-02 21:48:54', '2020-05-07 21:48:54', 'http://alimsatimcim.com/mobil/874223191.jpeg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.'),
(3, 2, 'Lorem ipsum dolor sit amet', NULL, NULL, '2020-05-02 21:48:54', '2020-05-07 21:48:54', 'http://alimsatimcim.com/mobil/874223191.jpeg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.'),
(4, 2, 'Lorem ipsum 1', NULL, NULL, '2020-05-03 22:05:13', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(5, 2, 'Lorem ipsum 2', NULL, NULL, '2020-05-03 22:05:13', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(6, 2, 'Lorem ipsum 3', NULL, NULL, '2020-05-03 22:05:13', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(7, 2, 'Lorem ipsum 4', NULL, NULL, '2020-05-03 22:05:13', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(8, 2, 'Lorem ipsum 5', NULL, NULL, '2020-05-03 22:05:13', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(9, 2, 'Lorem ipsum 6', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(10, 2, 'Lorem ipsum 7', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(11, 2, 'Lorem ipsum 8', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(12, 2, 'Lorem ipsum 9', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(13, 2, 'Lorem ipsum 10', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(14, 2, 'Lorem ipsum 11', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(15, 2, 'Lorem ipsum 12', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(16, 2, 'Lorem ipsum 13', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(17, 2, 'Lorem ipsum 14', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(18, 2, 'Lorem ipsum 15', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(19, 2, 'Lorem ipsum 16', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(20, 2, 'Lorem ipsum 17', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.');
INSERT INTO `products` (`id`, `categoryId`, `productName`, `productsPrice`, `productsTop`, `offerCreateTime`, `offerFinishedTime`, `productImage`, `productDescription`, `productSubDescription`) VALUES
(21, 2, 'Lorem ipsum 18', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(22, 2, 'Lorem ipsum 19', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(23, 2, 'Lorem ipsum 20', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(24, 2, 'Lorem ipsum 21', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(25, 2, 'Lorem ipsum 22', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(26, 2, 'Lorem ipsum 23', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(27, 2, 'Lorem ipsum 24', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(28, 2, 'Lorem ipsum 25', NULL, NULL, '2020-05-03 22:05:56', '2020-05-07 21:45:59', 'http://alimsatimcim.com/mobil/240912590.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam', 'Suspendisse a ipsum vestibulum, hendrerit velit et, elementum est. Morbi dictum purus eu mauris pretium auctor. Nulla vitae metus eget dui vestibulum maximus at a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque hendrerit nulla, id efficitur lacus posuere vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam nunc nunc, porttitor ac enim a, tempor mattis nunc. Duis tristique volutpat tempor. Fusce viverra elit non orci porttitor elementum.\r\n\r\nProin sed mollis lorem. Integer laoreet euismod nunc, in dictum nisl rutrum vel. Etiam rhoncus ornare nulla ut placerat. Vestibulum ante eros, faucibus sed orci vel, luctus lobortis leo. Proin id mauris et enim finibus tristique non at nisi. Nam tincidunt ultrices orci, non posuere erat tristique id. Praesent mauris quam, faucibus id diam at, interdum tincidunt nunc. Donec massa libero, fringilla sed est at, bibendum rhoncus nisl. Sed lectus justo, pulvinar ut ante ac, bibendum fermentum mi. Nullam a orci ut sapien malesuada rutrum. Cras ex metus, venenatis sit amet tristique a, laoreet ac diam. Donec lobortis sodales lorem a tincidunt. Cras ut hendrerit mauris. Nulla facilisi. Nam nec eros lobortis leo maximus mattis a a nulla. Etiam posuere, ante sit amet sagittis sollicitudin, diam elit laoreet neque, non sagittis mi leo quis massa.\r\n\r\nNullam urna augue, porttitor a tincidunt ac, bibendum et tellus. Integer faucibus odio eget dictum condimentum. Sed nisi dolor, congue volutpat suscipit ac, facilisis at orci. Nullam ultricies tellus orci, nec imperdiet felis dictum nec. Nullam condimentum blandit augue eget interdum. Praesent ullamcorper venenatis ante ac convallis. Curabitur eget ante quis nisl imperdiet luctus. Duis congue turpis nibh, ac euismod nulla malesuada eu. Nunc mattis felis quis aliquet mollis. Aliquam erat volutpat. Suspendisse potenti. Ut fermentum convallis aliquam. Nullam a luctus ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa velit, ullamcorper at auctor a, dignissim gravida augue.'),
(30, NULL, 'Deneme2', 299.99, 1, '2021-08-09 13:00:23', '2021-08-17 13:00:23', 'asuıhgdashıud', 'auıhsdhıuasdjn', 'asdasıpnuhdhıbjasd'),
(31, 1, 'webden eklenen1', 75, 1, '2020-05-02 21:48:54', '2020-05-08 21:48:59', NULL, 'Tahta.odun kesmeye yaran delici alet', 'asdasdasd'),
(33, 1, 'webden eklenen3', 25.99, 1, '2020-05-02 21:48:54', '2020-05-08 21:48:59', NULL, 'Tahta.odun kesmeye yaran delici alet', 'asdasdasd');

--
-- Dökümü yapılmış tablolar için kısıtlamalar
--

--
-- Tablo kısıtlamaları `offers`
--
ALTER TABLE `offers`
  ADD CONSTRAINT `offers_ibfk_1` FOREIGN KEY (`productId`) REFERENCES `products` (`id`);

--
-- Tablo kısıtlamaları `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`categoryId`) REFERENCES `productcategories` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
